[pytest]
addopts = --headed --slowmo 500

markers =
    smoke: critical smoke tests
    regression: full regression suite
    login: login related tests
    checkout: checkout flow tests
    cart: cart related tests
    